; TrailblazerGirl
; By. Salt
; Constants -------------------------

[Constants]
global persist $Arm = 0
global persist $Body = 0
global persist $Wrst = 0
global persist $Clth = 0
global persist $Neck = 0
global persist $Foot = 0
global persist $Glov = 0
global persist $Elbw = 0
global persist $Top = 0
global persist $Wing = 0
global persist $Hair = 0
global persist $Pupi = 0
global persist $BodyL = 0
global persist $WrstL = 0
global persist $Ribbon = 0
global persist $Bottom = 0

global $active
global $creditinfo = 0


[KeyArm]
condition = $active == 1
key = VK_NUMPAD7
type = cycle
$Arm = 0,1,2

[KeyBody]
condition = $active == 1
key = VK_NUMPAD5
type = cycle
$Body = 0,1,2,3,4,5

[KeyWrst]
condition = $active == 1
key = VK_NUMPAD4
type = cycle
$Wrst = 0,1,2,3,4

[KeyClth]
condition = $active == 1
key = VK_NUMPAD2
type = cycle
$Clth = 0,1,2

[KeyNeck]
condition = $active == 1
key = VK_NUMPAD8
type = cycle
$Neck = 0,1,2,3,4

[KeyGlov]
condition = $active == 1
key = VK_NUMPAD1
type = cycle
$Glov = 0,1,2

[KeyHair]
condition = $active == 1
key = VK_NUMPAD9
type = cycle
$Hair = 0,1

[KeyFoot]
condition = $active == 1
key = VK_NUMPAD3
type = cycle
$Foot = 0,1,2,3,4

[KeyElbw]
condition = $active == 1
key = +
type = cycle
$Elbw = 0,1	

global persist $Wing = 0

[KeyWing]
condition = $active == 1
key = VK_NUMPAD6
type = cycle
$Wing = 0,1

[KeyTop]
condition = $active == 1
key = VK_UP
type = cycle
$Top = 0,1,2

[KeyBottom]
condition = $active == 1
key = VK_DOWN
type = cycle
$Bottom = 0,1,2

[KeyPupi]
condition = $active == 1
key = k
type = cycle
$Pupi = 0,1,2


[KeyBodyL]
condition = $active == 1
key = VK_LEFT
type = cycle
$BodyL = 0,1

[KeyWrstL]
condition = $active == 1
key = VK_RIGHT
type = cycle
$WrstL = 0,1

[KeyRibbon]
condition = $active == 1
key = -
type = cycle
$Ribbon = 0,1,2

[Present]
post $active = 0


; Overrides -------------------------

[TextureOverrideTrailblazerGirlBodyBlend]
hash = b55c8431
handling = skip
vb2 = ResourceTrailblazerGirlBodyBlend
if DRAW_TYPE == 1
	vb0 = ResourceTrailblazerGirlBodyPosition
	draw = 313986, 0
elif DRAW_TYPE == 8
	Resource\SRMI\PositionBuffer = ref ResourceTrailblazerGirlBodyPositionCS
	Resource\SRMI\BlendBuffer = ref ResourceTrailblazerGirlBodyBlendCS
	$\SRMI\vertex_count = 313986
endif
$active = 1


[TextureOverrideTrailblazerGirlBodyTexcoord]
hash = f00b6ded
vb1 = ResourceTrailblazerGirlBodyTexcoord

[TextureOverrideTrailblazerGirlBodyDraw]
hash = d52d7139
override_vertex_count = 313986
override_byte_stride = 40
uav_byte_stride = 4

[TextureOverrideTrailblazerGirlHairBlend]
hash = a91c061e
handling = skip
vb2 = ResourceTrailblazerGirlHairBlend
if DRAW_TYPE == 1
	vb0 = ResourceTrailblazerGirlHairPosition
	draw = 11119, 0
elif DRAW_TYPE == 8
	Resource\SRMI\PositionBuffer = ref ResourceTrailblazerGirlHairPositionCS
	Resource\SRMI\BlendBuffer = ref ResourceTrailblazerGirlHairBlendCS
	$\SRMI\vertex_count = 11119
endif

[TextureOverrideTrailblazerGirlHairTexcoord]
hash = fe9eaef0
vb1 = ResourceTrailblazerGirlHairTexcoord

[TextureOverrideTrailblazerGirlHairDraw]
hash = 0f43f610
override_vertex_count = 11119
override_byte_stride = 40
uav_byte_stride = 4

[TextureOverrideTrailblazerGirlHeadBlend]
hash = aa50f051
handling = skip
vb2 = ResourceTrailblazerGirlHeadBlend
if DRAW_TYPE == 1
	vb0 = ResourceTrailblazerGirlHeadPosition
	draw = 3972, 0
elif DRAW_TYPE == 8
	Resource\SRMI\PositionBuffer = ref ResourceTrailblazerGirlHeadPositionCS
	Resource\SRMI\BlendBuffer = ref ResourceTrailblazerGirlHeadBlendCS
	$\SRMI\vertex_count = 3972
endif

[TextureOverrideTrailblazerGirlHeadTexcoord]
hash = 6d41cf70
vb1 = ResourceTrailblazerGirlHeadTexcoord

[TextureOverrideTrailblazerGirlHeadDraw]
hash = 9cfbc761
override_vertex_count = 3972
override_byte_stride = 40
uav_byte_stride = 4

[TextureOverrideTrailblazerGirlBodyIB]
hash = fba309df
handling = skip

[TextureOverrideTrailblazerGirlBodyA]
hash = fba309df
match_first_index = 0
ib = ResourceTrailblazerGirlBodyAIB
; TrailblazerGirlBodyA

; Arm 
if $Arm == 0
	drawindexed = 11184, 0, 0
	endif
if $Arm == 1
	drawindexed = 11514, 11184, 0
	endif
if $Arm == 2
	drawindexed = 11898, 22698, 0
	endif


; Body 
if $Body == 0
	drawindexed = 112182, 34596, 0
	endif
if $Body == 1
	drawindexed = 103071, 146778, 0
	endif
if $Body == 2
	drawindexed = 105231, 249849, 0
	endif
if $Body == 3
	drawindexed = 106833, 355488, 0
	endif
if $Body == 4
	drawindexed = 108114, 462321, 0
	endif
if $Body == 5
	drawindexed = 108966, 570435, 0
	endif

; Wrst 
if $Wrst == 0
	drawindexed = 6036, 1107309, 0
	endif
if $Wrst == 1
	drawindexed = 7680, 1113345, 0
	endif
if $Wrst == 2
	drawindexed = 6192, 1121025, 0
	endif
if $Wrst == 3
	drawindexed = 6384, 1127217, 0
	endif
if $Wrst == 4
	drawindexed = 6384, 1127217, 0
	endif

; Clth 
if $Clth == 0
	drawindexed = 27528, 679401, 0
	endif


; Foot 
if $Foot == 0
	drawindexed = 84516, 712881, 0
	endif
if $Foot == 1
	drawindexed = 35424, 797397, 0
	endif
if $Foot == 2
	drawindexed = 33675, 832821, 0
	endif
if $Foot == 3
	drawindexed = 34683, 866496, 0
	endif
if $Foot == 4
	drawindexed = 35043, 901179, 0
	endif

; Elbw 
if $Elbw == 0
	drawindexed = 5952, 706929, 0
	endif

; Glov 
if $Glov == 0
	drawindexed = 36144, 936222, 0
	endif
if $Glov == 1
	drawindexed = 62556, 972366, 0
	endif
if $Glov == 2
	drawindexed = 63468, 1034922, 0
	endif


; Wing 
if $Wing == 1	
	drawindexed = 8919, 1098390, 0
	endif

; Body003L
if $BodyL == 1
	drawindexed = 408, 355080, 0
	endif



; Wrst045L
if $WrstL == 1
	drawindexed = 168, 1133601, 0
	endif





[TextureOverrideTrailblazerGirlBodyB]
hash = fba309df
match_first_index = 32946
ib = ResourceTrailblazerGirlBodyBIB
; TrailblazerGirlBodyB-vb0=f05d06de.txt.007 (12667)

; Arm 
if $Arm == 0
	drawindexed = 3744, 0, 0
	endif
if $Arm == 1
	drawindexed = 6156, 3744, 0
	endif
if $Arm == 2
	drawindexed = 6156, 3744, 0
	endif

; WrstB
if $Wrst == 0
	drawindexed = 5112, 325833, 0
	endif
if $Wrst == 1
	drawindexed = 5112, 325833, 0
	endif
if $Wrst == 2
	drawindexed = 20886, 330945, 0
	endif
if $Wrst == 3
	drawindexed = 21954, 351831, 0
	endif
if $Wrst == 4
	drawindexed = 27330, 373785, 0
	endif

; Clth 
if $Clth == 0
	drawindexed = 28056, 89676, 0
	endif
if $Clth == 1
	drawindexed = 10155, 117732, 0
	endif


; Neck 
if $Neck == 1
	drawindexed = 13470, 141231, 0
	endif
if $Neck == 2
	drawindexed = 14724, 154701, 0
	endif
if $Neck == 3
	drawindexed = 18846, 169425, 0
	endif
if $Neck == 4
	drawindexed = 20100, 188271, 0
	endif

; FootB
if $Foot == 2
	drawindexed = 6081, 127887, 0
	endif
if $Foot == 3
	drawindexed = 7263, 133968, 0
	endif
if $Foot == 4
	drawindexed = 7263, 133968, 0
	endif

; Top 
if $Top == 0
	drawindexed = 6924, 208371, 0
	endif
if $Top == 1
	drawindexed = 110538, 215295, 0
	endif


; Bottom 
if $Bottom == 0
	drawindexed = 2505, 9900, 0
	endif
if $Bottom == 1
	drawindexed = 77271, 12405, 0
	endif

[TextureOverrideTrailblazerGirlHairIB]
hash = 1d62eafb
handling = skip

[TextureOverrideTrailblazerGirlHairA]
hash = 1d62eafb
match_first_index = 0
ib = ResourceTrailblazerGirlHairAIB
; TrailblazerGirlHairA

; Hair 
if $Hair == 0
	drawindexed = 16932, 0, 0
	endif
if $Hair == 1
	drawindexed = 19422, 16932, 0
	endif

; Ribbon 
if $Ribbon == 1
	drawindexed = 1158, 36354, 0
	endif
if $Ribbon == 2
	drawindexed = 8022, 37512, 0
	endif



[TextureOverrideTrailblazerGirlHeadIB]
hash = b6a70a49
handling = skip

[TextureOverrideTrailblazerGirlHeadA]
hash = b6a70a49
match_first_index = 0
ib = ResourceTrailblazerGirlHeadAIB
; TrailblazerGirlHeadA-vb0=19d09218.txt.00000 (3242)
drawindexed = 12942, 0, 0
; TrailblazerGirlHeadA

; Pupi 
if $Pupi == 0
	drawindexed = 732, 12942, 0
	endif
if $Pupi == 1
	drawindexed = 684, 13674, 0
	endif
if $Pupi == 2
	drawindexed = 624, 14358, 0
	endif

[TextureOverrideTrailblazerGirlHeadB]
hash = b6a70a49
match_first_index = 12636
ib = ResourceTrailblazerGirlHeadBIB
; TrailblazerGirlHeadB-vb0=19d09218.txt.001 (56)
drawindexed = 156, 0, 0

[TextureOverrideTrailblazerGirlBodyADiffuse]
hash = 78d10c03
this = ResourceTrailblazerGirlBodyADiffuse

[TextureOverrideTrailblazerGirlBodyALightMap]
hash = 69014337
this = ResourceTrailblazerGirlBodyALightMap

[TextureOverrideTrailblazerGirlHairADiffuse]
hash = a04fcf6f
this = ResourceTrailblazerGirlHairADiffuse

[TextureOverrideTrailblazerGirlHairALightMap]
hash = 02a9b085
this = ResourceTrailblazerGirlHairALightMap

[TextureOverrideTrailblazerGirlHeadADiffuse]
hash = 4e98df53
this = ResourceTrailblazerGirlHeadADiffuse


; CommandList -----------------------


; Resources -------------------------

[ResourceTrailblazerGirlBodyPosition]
type = Buffer
stride = 40
filename = TrailblazerGirlBodyPosition.buf

[ResourceTrailblazerGirlBodyBlend]
type = Buffer
stride = 32
filename = TrailblazerGirlBodyBlend.buf

[ResourceTrailblazerGirlBodyTexcoord]
type = Buffer
stride = 20
filename = TrailblazerGirlBodyTexcoord.buf

[ResourceTrailblazerGirlBodyPositionCS]
type = StructuredBuffer
stride = 40
filename = TrailblazerGirlBodyPosition.buf

[ResourceTrailblazerGirlBodyBlendCS]
type = StructuredBuffer
stride = 32
filename = TrailblazerGirlBodyBlend.buf

[ResourceTrailblazerGirlBodyAIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = TrailblazerGirlBodyA.ib

[ResourceTrailblazerGirlBodyBIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = TrailblazerGirlBodyB.ib

[ResourceTrailblazerGirlHairPosition]
type = Buffer
stride = 40
filename = TrailblazerGirlHairPosition.buf

[ResourceTrailblazerGirlHairBlend]
type = Buffer
stride = 32
filename = TrailblazerGirlHairBlend.buf

[ResourceTrailblazerGirlHairTexcoord]
type = Buffer
stride = 8
filename = TrailblazerGirlHairTexcoord.buf

[ResourceTrailblazerGirlHairPositionCS]
type = StructuredBuffer
stride = 40
filename = TrailblazerGirlHairPosition.buf

[ResourceTrailblazerGirlHairBlendCS]
type = StructuredBuffer
stride = 32
filename = TrailblazerGirlHairBlend.buf

[ResourceTrailblazerGirlHairAIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = TrailblazerGirlHairA.ib

[ResourceTrailblazerGirlHeadPosition]
type = Buffer
stride = 40
filename = TrailblazerGirlHeadPosition.buf

[ResourceTrailblazerGirlHeadBlend]
type = Buffer
stride = 32
filename = TrailblazerGirlHeadBlend.buf

[ResourceTrailblazerGirlHeadTexcoord]
type = Buffer
stride = 8
filename = TrailblazerGirlHeadTexcoord.buf

[ResourceTrailblazerGirlHeadPositionCS]
type = StructuredBuffer
stride = 40
filename = TrailblazerGirlHeadPosition.buf

[ResourceTrailblazerGirlHeadBlendCS]
type = StructuredBuffer
stride = 32
filename = TrailblazerGirlHeadBlend.buf

[ResourceTrailblazerGirlHeadAIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = TrailblazerGirlHeadA.ib

[ResourceTrailblazerGirlHeadBIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = TrailblazerGirlHeadB.ib

[ResourceTrailblazerGirlBodyADiffuse]
filename = TrailblazerGirlBodyADiffuse.dds

[ResourceTrailblazerGirlBodyALightMap]
filename = TrailblazerGirlBodyALightMap.dds

[ResourceTrailblazerGirlHairADiffuse]
filename = TrailblazerGirlHairADiffuse.dds

[ResourceTrailblazerGirlHairALightMap]
filename = TrailblazerGirlHairALightMap.dds

[ResourceTrailblazerGirlHeadADiffuse]
filename = TrailblazerGirlHeadADiffuse.dds


; .ini generated by XXMI (XX-Model-Importer) v1.5.8
; If you have any issues or find any bugs, please open a ticket at https://github.com/leotorrez/XXMI-Tools/issues
